* TODO this isntaller should bail if write protect is on

At the moment installer doesn't check

* TODO don't use taskkill in settings.ps1

Use something more PS'ish possibly job-control stuff?

* DONE pu is working, but clean it up
  CLOSED: [2016-08-08 Mon 19:50]

I started don't-run-twice in =tm/bestPerformance= and then changed how I
did it in tm/dontruntwice.

tm/bestPerformance
tm/dontruntwice

* DONE Re-evaluate whether each function should be run just once
  CLOSED: [2016-08-08 Mon 19:51]

Its enough to delete registry key =HKCU:\Software\Streambox\win_settings=

These two were just added, but there is no check yet as to whether
theyve been run before. I think they should run just once, but we should
also then have a -force option to run despite having already been run.

tm/bestPerformance
tm/set-processorscheduling

* DONE Never tried uninsaller, make sure it works
  CLOSED: [2016-07-29 Fri 09:43]
* DONE Each time this runs IE complains about not being closed properly
  CLOSED: [2016-07-28 Thu 20:34]

Each time this runs IE complains about not being closed properly. Maybe
leave cookie behind and don't run twice per account?

* DONE Make sure this works with FBWF write protect on
  CLOSED: [2016-07-29 Fri 02:05]

